In [16]:
import datetime
import csv

def get_file_rows(path):
    with open(path) as file:
        lines = file.readlines()
        print(lines.pop(0).split('\t')) # pop header
        out = list()
        for l in lines:
            out.append(l.split('\t'))
        return out

def ageInYears( d ):
    today = datetime.date.today()
    currentYrAnniversary = datetime.date( today.year, d.month, d.day )
    return (today.year - d.year) - (1 if today < currentYrAnniversary else 0)


socio_keys = ['idade', 'genero', 'etnia', 'estado_civil', 'trabalha', 'filhos', 'renda', 'no_enem', 'curso_escolha',  'motivacao', 'dominio_pc', 'dominio_lingua', 'ano_conclusao', 'curso_ingresso']
socio = {name: idx for idx, name in enumerate(socio_keys)}
#help(enumerate)

def filter_cols(data_source: list, cols: list ):
    return [row[socio[col]] for col in cols for row in data_source]

tsv_rows = get_file_rows('../dados/socioeconomico_2019.tsv')
idades = filter_cols(tsv_rows, ['idade'])

Help on class enumerate in module builtins:

class enumerate(object)
 |  enumerate(iterable[, start]) -> iterator for index, value of iterable
 |
 |  Return an enumerate object.  iterable must be another object that supports
 |  iteration.  The enumerate object yields pairs containing a count (from
 |  start, which defaults to zero) and a value yielded by the iterable argument.
 |  enumerate is useful for obtaining an indexed list:
 |      (0, seq[0]), (1, seq[1]), (2, seq[2]), ...
 |
 |  Methods defined here:
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  __next__(self, /)
 |      Implement next(self).
 |
 |  __reduce__(...)
 |      Return state information for pickling.

['Idade', 'Gênero', 'Etnia', 'Estado Civil', 'Trabalha', 'Filhos', '6. Renda familiar fixa', 'Quantidade de vezes que fez o ENEM', 'Curso Desejado', 'Motivação', 'Domínio do computador', 'Língua Estrangeira', 'Conclusão Ensino Médio', 'Curso de Ingresso\n']

['18 a 20',
 '17 ou menos',
 '18 a 20',
 '17 ou menos',
 '17 ou menos',
 '17 ou menos',
 '18 a 20',
 '21 a 29',
 '18 a 20',
 '30 a 39',
 '18 a 20',
 '18 a 20',
 '21 a 29',
 '17 ou menos',
 '18 a 20',
 '21 a 29',
 'Acima de 50 anos',
 '21 a 29',
 '18 a 20',
 '18 a 20',
 '21 a 29',
 '21 a 29',
 '18 a 20',
 '18 a 20',
 '21 a 29',
 '21 a 29',
 '30 a 39',
 '21 a 29',
 '17 ou menos',
 '21 a 29',
 '17 ou menos',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '18 a 20',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '18 a 20',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '18 a 20',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '18 a 20',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '30 a 39',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '30 a 39',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '30 a 39',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '30 a 39',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '21 a 29',
 '30 a 39',
 '18 a 20']